---
:api_key: e975c5b7699d25f58a191e50661d4537
:password: ee5fc645e896555ab9ec1eb0b9930ef4
:store: poppy-lissiman-2.myshopify.com
:theme_id: 
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
:ignore_files:
- sass/
- config/settings_data.json
- node_modules/