---
:api_key: 8286396bcc02b239223fea8d2a37e6a8
:password: 53b412d011452dba61001b64c13327b0
:store: poppy-lissiman-3.myshopify.com
:theme_id: 
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
:ignore_files:
- css/
- config/settings_data.json
- node_modules/
